page_title              : PhotoStacks · Photo Organizer # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id              : 1640800072                    # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country         : us                            # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
appstore_link           :                               # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link          :                               # Enter Google Play Store URL.
presskit_download_link  :                               # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                        # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").
app_icon                : assets/appicon.png            # Automatically populates if not set and if iOS app ID is set. Otherwise enter path to icon file manually.
app_name                : PhotoStacks                   # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
app_price               : Free                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
app_description         : Fast and simple manual photo organization helper.
enable_smart_app_banner : true                          # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name               : Vitya Poekhal
your_link               : https://instagram.com/vityapoekhal
your_city               :
email_address           :
facebook_username       : vityapoekhal
instagram_username      : vityapoekhal
twitter_username        : vityapoekhal
github_username         : vityapoekhal
youtube_username        : UC57HY7GHQZrTS4PY5uOroaA

# Feature List              → Edit, add or remove features to be presented.
features                    :

  - title                   : Highest Sorting Quality
    description             : Would an artificial intelligence be able to understand why you care about this or that picture? Manual sorting won't give the machine a chance to make an irreversible mistake.
    fontawesome_icon_name   : gem

  - title                   : Speed and Ease of Use
    description             : With the conveyorized approach, sorting takes noticeably less time compared to the standard application.
    fontawesome_icon_name   : rabbit-running

  - title                   : Intuitive User Interface
    description             : You don't have to figure it out or adapt. All it takes is one finger to work.
    fontawesome_icon_name   : rocket-launch

  - title                   : Sorting by Albums
    description             : Maximum sorting efficiency by using albums. You can rotate the device sideways and work horizontally to fit more albums on one page.
    fontawesome_icon_name   : folder-tree

  - title                   : Room for Doubt
    description             : If no album fits the photo, you can postpone the decision for later by scrolling the carousel to the next photo.
    fontawesome_icon_name   : face-thinking

# Theme Settings
topbar_color                   : "#000000"
topbar_transparency            : 0.3
topbar_title_color             : "#ffffff"

cover_image                    : assets/headerimage.jpg              # Replace with alternative image path or image URL.
cover_overlay_color            : "#000000"
cover_overlay_transparency     : 0.0

device_color                   : black                               # Set to: blue, black, yellow, coral or white.
body_background_color          : "#ffffff"
link_color                     : "#1d63ea"

app_title_color                : "#000000"
app_price_color                : "#000000"
app_description_color          : "#000000"

feature_title_color            : "#000000"
feature_text_color             : "#666666"

feature_icons_foreground_color : "#1d63ea"
feature_icons_background_color : "#e6e6e6"

social_icons_foreground_color  : "#666666"
social_icons_background_color  : "#e6e6e6"

footer_text_color              : "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
